import { UserStatus } from '../../user-status/entities/user-status.entity';
import { Role } from '../../role/entities/role.entity';
import { Department } from '../../department/entities/department.entity';
import { Faculty } from '../../faculty/entities/faculty.entity';
import { Level } from '../../level/entities/level.entity';
import { Country } from '../../country/entities/country.entity';

interface UserAttachment {
   _id : number;
  updated_on: Date;
  created_on: Date;
  name: string;
  description: string;
  abbreviation: string;
  user_id: number;
  user: IUser;
  location: string;
  mimetype: string;
  size: string;
  key: string;
  author_name: string;


  getId(): number;
  setId(id: number): void;
  getCreatedOn(): Date;
  setCreatedOn(created_on: Date): void;
  getName(): string;
  setName(name: string): void;
  getAbbreviation(): string;
  setAbbreviation(abbreviation: string): void;
  getDescription(): string;
  setDescription(description: string): void;
  getUpdatedOn(): Date;
  setUpdatedOn(updated_on: Date): void;
  getLocation(): string;
  setLocation(location: string): void;
  getMimetype(): string;
  setMimetype(mimetype: string): void;
  getSize(): string;
  setSize(size: string): void;
  getKey(): string;
  setKey(key: string): void;
  getAuthorName(): string;
  setAuthorName(author_name: string): void;
  getUserId(): number;
  setUserId(user_id: number): void;
  getUser(): IUser;
  setUser(user: IUser): void;
}


export interface IUser {

/*   _id : number;
  updated_on: Date;
  created_on: Date;
  first_name: string;
  last_name: string;
  about: string;
  matriculation_number: string;
  department: Department;
  faculty: Faculty;
  level: Level;
  country: Country;
  department_id: number;
  faculty_id: number;
  level_id: number;
  country_id: number;
  email_address: string;
  username: string;
  password: string;
  confirm_password: string;
  hash: string;
  salt: string;
  user_full_name: string;
  user_email_address: string;
  role: string[] | string | number[];
  user_role_id: number;
  status: UserStatus;
  user_profile_photo: UserAttachment;
  user_signature: UserAttachment;
  roles: Role[];
  status_id: number;
  reset_password_token: string;
  reset_password_expires: string;
*/
  getCreatedOn(): Date;
  setCreatedOn(created_on: Date): void;
  getEmailAddress(): string;
  setEmailAddress(email_address: string): void;
  getUsername(): string;
  setUsername(username: string): void;
  getHash(): string;
  getSalt(): string;
  getRole(): number[];
  getStatus(): UserStatus;
  setStatus(status: UserStatus): void;
  getUserProfilePhoto(): UserAttachment;
  setUserProfilePhoto(user_profile_photo: UserAttachment): void;
  getUserSignature(): UserAttachment;
  setUserSignature(user_signature: UserAttachment): void;
  getUserRoleId(): number;
  setRole(role: number[]): void;
  setSalt(salt: string): void;
  setHash(hash: string): void;
  getRoles(): Role[];
  setRoles(roles: Role[]): void;
  addRole(role: Role): void;
  getPassword(): string;
  setPassword(password: string): void;
  getConfirmPassword(): string;
  setConfirmPassword(password: string): void;
  getStatusId(): number;
  getResetPasswordToken(): string;
  setResetPasswordToken(reset_password_token: string): void;
  getResetPasswordExpires(): string;
  setResetPasswordExpires(reset_password_expires: string): void;
  getUserFullName(): string;
  setUserFullName(user_full_name: string): void;
  getUserEmailAddress(): string;
  setUserEmailAddress(user_email_address: string): void;
  getFirstName(): string;
  setFirstName(first_name: string): void;
  getLastName(): string;
  setLastName(last_name: string): void;
  getAbout(): string;
  setAbout(about: string): void;
  getMatriculationNumber(): string;
  setMatriculationNumber(matriculation_number: string): void;
  getDepartment(): Department;
  setDepartment(department: Department): void;
  getFaculty(): Faculty;
  setFaculty(faculty: Faculty): void;
  getLevel(): Level;
  setLevel(level: Level): void;
  getCountry(): Country;
  setCountry(country: Country): void;
  getDepartmentId(): number;
  getFacultyId(): number;
  getLevelId(): number;
  getCountryId(): number;

}

